// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MetaDataProvider.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::metadata;

class MetaDataProviderHandler : virtual public MetaDataProviderIf {
 public:
  MetaDataProviderHandler() {
    // Your initialization goes here
  }

  void initializeConfig(const MetaDataConfig& config) {
    // Your implementation goes here
    printf("initializeConfig\n");
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void informManagedRegion(const int32_t serverId, const  ::core::Region& region) {
    // Your implementation goes here
    printf("informManagedRegion\n");
  }

  void getRoutingInfo(RoutingInfo& _return) {
    // Your implementation goes here
    printf("getRoutingInfo\n");
  }

  void nodeJoin(const NodeId& nodeId) {
    // Your implementation goes here
    printf("nodeJoin\n");
  }

  void nodeRemove(const NodeId& nodeId) {
    // Your implementation goes here
    printf("nodeRemove\n");
  }

  void reShardRegion(const  ::core::Region& region) {
    // Your implementation goes here
    printf("reShardRegion\n");
  }

  void resetSharding() {
    // Your implementation goes here
    printf("resetSharding\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MetaDataProviderHandler> handler(new MetaDataProviderHandler());
  shared_ptr<TProcessor> processor(new MetaDataProviderProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

